# Generated by Django 2.1 on 2019-06-17 21:40

from django.db import migrations, models
import django.db.models.deletion
import payment.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentSumm', models.IntegerField()),
                ('userLogin', models.CharField(max_length=120)),
                ('userEmail', models.EmailField(max_length=254)),
                ('inputTime', models.TimeField(auto_now_add=True)),
                ('confirm', models.BooleanField(blank=True)),
                ('description', models.TextField()),
                ('confirmTime', models.TimeField(default=payment.models.get_delta)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payment.Payment')),
            ],
        ),
    ]
