# Generated by Django 2.1 on 2019-06-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='userLogin',
            field=models.CharField(max_length=120),
        ),
    ]
