# Generated by Django 2.1 on 2019-06-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20190616_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='confirm',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='inputTime',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
